"""create brands and candidates

Revision ID: 990d0b9dae31
Revises: 
Create Date: 2026-08-17 16:54:39.567260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '990d0b9dae31'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    candidate_status = postgresql.ENUM(
        "pending", "crawled", "scored", "dismissed",
        name="candidate_status",
        create_type=False,
    )
    candidate_status.create(op.get_bind(), checkfirst=True)
    op.create_table('brands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('official_domain', sa.String(length=255), nullable=False),
    sa.Column('keywords', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('match_reason', sa.String(length=60), nullable=False),
    sa.Column("status", candidate_status, nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidates_domain'), 'candidates', ['domain'], unique=True)
    op.create_index(op.f('ix_candidates_first_seen_at'), 'candidates', ['first_seen_at'], unique=False)
    op.create_index(op.f('ix_candidates_status'), 'candidates', ['status'], unique=False)
    op.create_index('ix_candidates_status_first_seen', 'candidates', ['status', 'first_seen_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidates_status_first_seen', table_name='candidates')
    op.drop_index(op.f('ix_candidates_status'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_first_seen_at'), table_name='candidates')
    op.drop_index(op.f('ix_candidates_domain'), table_name='candidates')
    op.drop_table('candidates')
    op.execute("DROP TYPE IF EXISTS candidate_status")
    op.drop_table('brands')
    # ### end Alembic commands ###
